### ISSUE TITLE
Create a deployment script for setting up the database

### ISSUE THREAD

**Issue by ChristinaWa** [dboehmer/coocook#1]
Sowas in der Art wolltest du noch machen oder die Config für das Generieren der Tabellen oder so.

**Comment by dboehmer** [comment]
I wanted to create a scrip that deploys the database tables from scratch. Done it bb2aeb52.

Call `script/coocook_deploy.pl --help` for options.

**Comment by dboehmer** [comment]
I had a chat with @shadowcat-mst and was convinced `App::DH` + `DBIx::Class::Schema::Config` is a better solution than loading the whole application to get `$c->model('Schema')`. I migrated in 6ebf69d.

To deploy the database you now need to run:

    script/coocook_deploy.pl install

**Comment by ChristinaWa** [comment]
Is there any configuration needed? I installed APP::DH but I get the message `DBIx::Class::Storage::DBI::_connect(): You did not provide any connection_info at C:/Strawberry/perl/site/lib/App/DH.pm line 196`

**Comment by dboehmer** [comment]
Actually, everything should be configured correctly from the new files.

A short excursion:

Perl's database interface `DBI` use a DSN string to read the connection information. In plain old Perl you'd write

    my $dbh = DBI->connect("dbi:SQLite:coocook.sqlite");

In this setup it's a little bit more complex:

1. `DBIx::Class` is a database ORM that uses `DBI` in the background and passes the DSN along.
1. `DBIx::Class::Schema::Config` is a subclass that reads [a bunch of config files](https://metacpan.org/pod/DBIx::Class::Schema::Config#CONFIG-FILES) that may define several named database connections. Applications using such schemata may provide only the name of a predefined connection`
1. `Coocook::Schema` is such a schema.

Also with have two applications:

1. `Coocook` is a Catalyst app. It reads the config from `coocook.conf` and passes the database name to the schema.
1. `Coocook::Schema::DeploymentHandler` is a subclass of `App::DH` and presets the schema class to our `Coocook::Schema`.

I tested this and in my environment `App::DH` uses the `development` database from `dbic.yaml`.

Try to pass the database name to `scripts/coocook_deploy.pl` with the `-c` option.

    scripts/coocook_deploy.pl -cdevelopment

Does that work for you? Alternatively `App::DH` might not have found the `dbic.yaml`. Try to copy it to another one of the possible locations or explicitly set the environment variable `DBIX_CONFIG_DIR`.

**Comment by ChristinaWa** [comment]
After putting `dbic.yaml` into the root folder and using the flag `-cdevelopment` I get the following message:
`Can't opendir($fh, 'share\ddl\SQLite\deploy\1'): No such file or directory at C:/Strawberry/perl/site/lib/DBIx/Class/DeploymentHandler/DeployMethod/SQL/Translator.pm line 109
DBIx::Class::Storage::TxnScopeGuard::DESTROY(): A DBIx::Class::Storage::TxnScopeGuard went out of scope without explicit commit or error. Rolling back. at C:\Users\Christina\coocook\script\coocook_deploy.pl line 0`

**Comment by dboehmer** [comment]
Do you mean the folder `root` or the project's root folder? The file should be in the ladder one in the current master branch.

Do you understand the error message yourself? DBIx::Class is looking for SQL for [this folder](https://github.com/dboehmer/coocook/tree/master/share/ddl/SQLite/deploy/1) that *should* be there and reachable from the current working directory.

1. Is it there?
2. Are you running the script from the project's root folder?
3. Take a look at [`App::DH`'s options](https://metacpan.org/pod/App::DH#PARAMETERS). Mind the default value for the DDL dir, try to explicitly set it, e.g. to the absolute path.

**Comment by ChristinaWa** [comment]
Works after using command `script/coocook_deploy.pl install`.
Renamed old sqlite-file to get the new one created.
