### ISSUE TITLE
Change incrementation of number input element at recipes

### ISSUE THREAD

**Issue by ChristinaSi** [dboehmer/coocook#10]
The value of ingredients increments at the third decimal place by klicking up. That's not wanted behavior.

**Comment by dboehmer** [comment]
Reason is 1cf7789930d334ffe306bdf35bdd1463684af923. Unfortunately the `step` attribute affects both the number of decimal places and the offset by clicking the buttons once.

**Comment by dboehmer** [comment]
Fixed by bf8f51b7fa159e4333137cebe5e700b10fc9efdf
