### ISSUE TITLE
No tests for Controller::Meal

### ISSUE THREAD

**Issue by moseschmiedel** [dboehmer/coocook#114]
At the moment I can write anything dumb, like for example `die`  in `Controller::Meal` and the tests don't cover it and everything compiles fine.

**Comment by dboehmer** [comment]
@moseschmiedel You mean adding a `die()` *inside* any action methods, don’t you? Any compile time errors or code that is run at startup time will make the application fail and should definitely be covered by `compile.t` and `01app.t`.

**Comment by dboehmer** [comment]
@moseschmiedel Thank you for raising this issue! :+1: 

Adding a simple list of GET requests increasing our test coverage by +9%.

Are you already satisfied with this test? What else do you require?

**Comment by dboehmer** [comment]
@moseschmiedel still waiting for a reply :smile:

**Comment by moseschmiedel** [comment]
I wrote some tests for the full lifecycle of meals.
