### ISSUE TITLE
Sending the verification email for user creation from the Docker image fails

### ISSUE THREAD

**Issue by MarkusLeupold** [dboehmer/coocook#154]
#### The issue
I just installed the Docker image (coocook/coocook-dev:latest) on my machine and tried to run my coocook fork inside it. The server started without any registered user, so I tried to create one. The problem is, that the verification email didn't arrive in my inbox (including the _unknown_ and _spam_ folders). This means, that I can't use the Docker image for development at the moment until a solution is found.

#### Additional information:
My fork is currently equal to the upstream repo and on branch master. No significant changes have been made.

This is the server log section which could contain some relevant information:
```
[info] *** Request 19 (0.173/s) [8] [Fri Feb 12 11:20:22 2021] ***
[debug] Path is "/user/post_register"
[info] Would set HTTP Strict Transport Security header if HTTPS
[debug] Strict-Transport-Security: max-age=31536000
[debug] "POST" request for "register" from "172.17.0.1"
[debug] Body Parameters are:
.-----------+-----------------------.
| Parameter | Value                 |
+-----------+-----------------------+
| email     | markus.leupold@web.de |
| password  | 1234                  |
| password2 | 1234                  |
| username  | markus                |
'-----------+-----------------------'
[debug] Found sessionid "655dec0c457bc200056ce910a78c3bdbaee8d44d" in cookie
[debug] Restored session "655dec0c457bc200056ce910a78c3bdbaee8d44d"
[warn] Not redirecting to HTTPS in debug mode
[debug] Rendering template "error/forbidden.tt"
[debug] Response Code: 403; Content-Type: text/html; charset=utf-8; Content-Length: unknown
[info] Request took 0.030432s (32.860/s)
.----------------------------------+-----------.
| Action                           | Time      |
+----------------------------------+-----------+
| /begin                           | 0.002707s |
| /auto                            | 0.004476s |
| /base                            | 0.000114s |
| /user/post_register              | 0.003913s |
|  -> /error/forbidden             | 0.000173s |
| /end                             | 0.004098s |
|  -> Coocook::View::HTML->process | 0.003225s |
'----------------------------------+-----------'
```

**Comment by MarkusLeupold** [comment]
I tried to send a password recovery mail and it helped:
- I still didn't receive an email in my inbox
- The server log luckily told the content of the mail (which it did not do for the verification mail). I opened the password reset link and coocook told me that my email is now verified and let me change my password. Now I am logged in.

**Comment by dboehmer** [comment]
For some reason the server returned a 403 forbidden error. Did you try to create a user multiple times or in different tabs?

With an empty user database you should see an info box at the top that the first user will be site owner and it should be free to register. Only for the second, third, … user you need to enable user registration in the config.

Maybe the first email was dumped on the terminal but you tried more requests after that?

**Comment by dboehmer** [comment]
We successfully setup @kuro610 @tjfoerster today with a Docker container and they could catch the email in their Docker terminal. Please reopen if problem persists for you.
