### ISSUE TITLE
Remove jQuery

### ISSUE THREAD

**Issue by dboehmer** [dboehmer/coocook#155]
We’re now using Bootstrap and with modern Javascript jQuery is told to be not necessary anymore. We’ve probably have a total of 155 lines of jQuery code:

```console
$ ack '\$\(' root/static/js/ -l | xargs wc -l
  11 root/static/js/article/edit.js
  47 root/static/js/recipe/import/preview.js
  44 root/static/js/user/register.js
  53 root/static/js/script.js
 155 total
```

- [x] [`root/static/js/article/edit.js`](https://github.com/dboehmer/coocook/blob/master/root/static/js/article/edit.js)
- [x] [`root/static/js/script.js`](https://github.com/dboehmer/coocook/blob/master/root/static/js/script.js)
- [x] [`root/static/js/user/register.js`](https://github.com/dboehmer/coocook/blob/master/root/static/js/user/register.js)
- [x] [`root/static/js/recipe/import/preview.js`](https://github.com/dboehmer/coocook/blob/master/root/static/js/recipe/import/preview.js)
- [x] remove jQuery files and includes
- [x] migrate Bootstrap to v5.1.3

**Comment by tjfoerster** [comment]
@dboehmer We are using Boostrap 4 which requires jQuery. So we should upgrade to Bootstrap 5. This also gives us new possibilities for a modern ui.

https://getbootstrap.com/docs/5.0/migration/

**Comment by dboehmer** [comment]
> @dboehmer We are using Boostrap 4 which requires jQuery. So we should upgrade to Bootstrap 5. This also gives us new possibilities for a modern ui. What do you think?
> 
> https://getbootstrap.com/docs/5.0/migration/

Upgrading Bootstrap sounds good :+1: Especially if that removes a dependency on jQuery! Can you apply that and test it? I think Git history for the bootstrap branch should show which pages very touched for Bootstrap.
