### ISSUE TITLE
Fix warning in Controller::Recipe

### ISSUE THREAD

**Issue by dboehmer** [dboehmer/coocook#23]
> "my" variable $input_okay masks earlier declaration in same statement at /home/daniel/workspace/coocook/script/../lib/Coocook/Controller/Recipe.pm line 73, <DATA> line 1.

You just have to look for multiple `my $input_okay` statements. Can you fix that?

**Comment by ChristinaWa** [comment]
Fixed bug.

**Comment by dboehmer** [comment]
Fixed in  e77b58f.
