### ISSUE TITLE
Transform articles, units, … pages into subpages of project

### ISSUE THREAD

**Issue by ChristinaWa** [dboehmer/coocook#3]
The select button in the project overview has no real benefit at the moment. Change it so that you can really select projects with it or delete it.

**Comment by dboehmer** [comment]
I think we should have main menu and a project-specific menu on all pages related to any particular project. Just like on Github where you have *Code*, *Issues* etc. links per project.

**Comment by dboehmer** [comment]
Done with a2994a7
