### ISSUE TITLE
Edit design of error message

### ISSUE THREAD

**Issue by ChristinaWa** [dboehmer/coocook#30]
In the new surface the error message is displayed in the header. Put it in the content part and change its look.

**Comment by dboehmer** [comment]
I think this issue would have been closed automatically as your commit message adheres to https://help.github.com/articles/closing-issues-via-commit-messages/ but not before your commit was merged into `master`. Let's try that next time and do not close the issue by hand:-)

**Comment by ChristinaWa** [comment]
I knew but I like to finish things so I just made it by hand. But if you don't like this I'll leave it.
