### ISSUE TITLE
Changing dish ingredients doesn't affect purchase list item's value

### ISSUE THREAD

**Issue by dboehmer** [dboehmer/coocook#33]
Steps to reproduce:

1. create dish with ingredient
2. add ingredient to purchase list
3. change value of ingredient

Actual result: purchase list item still holds old value

Expected result: purchase list item is updated

Open questions: How to handle purchase list items with value changed by hand, e.g. ceiled number? Maybe save if value was edited by hand and warn if?

**Comment by moseschmiedel** [comment]
This bug is also triggered, when deleting a meal which has ingredients, that have items assigned to it, which already got placed on a purchase list.

**Comment by moseschmiedel** [comment]
Also when deleting a dish.
