### ISSUE TITLE
Project editor: nested forms with dish deletion and meal update don't work

### ISSUE THREAD

**Issue by dboehmer** [dboehmer/coocook#45]
Firefox correctly claims that nested `<form>`s don't work. I didn't test other browsers yet.

Problem in the project editor is that the list of meals & dishes is a large table. The are small forms inside the table to edit meals and dishes. Also there is a larger outer form to delete selected dishes.

* Originally the first form in the table doesn't work because Firefox deems it invalid. All remaining forms work.
* As a workaround I put `<form></form>` inside the outer form above the table. Now all inner forms work but the outer one is broken because the `<form>` is deemed invalid and `</form>` closes the outer form.

How to fix this? Ideas:
* work with 1 super form submitting to 1 master controller method and different submit buttons with distinguishable identifiers
* redesign the whole page which is bloated anyway

**Comment by ChristinaWa** [comment]
Resolution from meeting number 8:

- delete check boxes which don't work anyway
- provide deletion of dishes in the subpage of the dish
- mass manipulation of dishes is not available at the moment, delete respective box
- mass manipulation will be in an extra page some time in the future
- later we want to create a menu button for each dish and meal and project to delete and manipulate the element in question (like in the dropbox directory listing)
