### ISSUE TITLE
Handle purchase list item when deleting meal, dish or dish ingredient

### ISSUE THREAD

**Issue by dboehmer** [dboehmer/coocook#47]
Should the delete action be prohibited or what should be done with the purchase list item?

__Caution:__ Not yet implemented but planned is that the purchase list item can have an offset, e.g. to get a rounded value. Example: 400g + 0.5kg = 0.9kg. An offset of +0.1kg is used to get exactly 1kg. Now if 400g is deleted 0.5kg+0.1kg remains …

**Comment by moseschmiedel** [comment]
very similar to #33

**Comment by moseschmiedel** [comment]
There should be a way for the user to interact with the offset feature of items.

**Comment by moseschmiedel** [comment]
Working: 
- deleting dish
- deleting dish_ingredient

Not even implemented:
- deleting meal

**Comment by moseschmiedel** [comment]
TODO: implement meal deletion
