### ISSUE TITLE
Supply default error page

### ISSUE THREAD

**Issue by ChristinaWa** [dboehmer/coocook#6]
Add template and controller for default error page.

**Comment by dboehmer** [comment]
Are you sure this is a duplicate? Can't find the other one. Beware this is about internal server errors and replacing Catalyst's default error template, not about displaying user errors. Please link duplicate or reopen.

**Comment by ChristinaWa** [comment]
The other one is #18. At least this is what I meant when I wrote this issue. If you want to you can reopen and add a description about replacing Catalyst's default error template or create a new issue.
