### ISSUE TITLE
Add function to import data from other projects

### ISSUE THREAD

**Issue by ChristinaWa** [dboehmer/coocook#7]
There is one import dialog:
You can choose the project to import data from.
There are several options which part of the project you want to import:

- units

- units, recipes, articles -> additionally you can choose if you want to import recipes and articles with their tags

- units, articles -> additionally you can choose if you want to import articles with their tags

Additionally you can choose if you want to import the following:

- shop sections

- tags

You can not import meals.

**Comment by dboehmer** [comment]
Completed by 18dcb7d6.
