### ISSUE TITLE
Implement settings bar

### ISSUE THREAD

**Issue by ChristinaSi** [dboehmer/coocook#80]
The settings bar (green one on top, only desktop version yet) should be implemented depending on the state (signed in, not yet signed in, after sign out).

Important:

- Add links to register and login page

- Add messages on the right according to the picture

- Add effect when hovering or clicking on menu items

![menu_ubersicht](https://user-images.githubusercontent.com/17025347/46877347-efba6880-ce40-11e8-8685-6fe5c7a67903.png)

**Comment by dboehmer** [comment]
> @dboehmer could you please provide a possibility to check if user has just logged out in html?
> Then we could show the message that the user has successfully logged out according to the picture above.

That was done in ce87d8d16530d7e7a89ab8bcec4a4ef798f24911 and was the last missing bit of this issue.
