### ISSUE TITLE
Implement top navigation bar

### ISSUE THREAD

**Issue by ChristinaSi** [dboehmer/coocook#81]
The top navigation bar (grey one) holds all important menu items. Its items vary depending on the state (signed in, signed out, project chosen).

Important:

- Add all menu items depending on the state

- Correctly link to all pages

- Add highlight effect when hovering or clicking on menu items

![menu_ubersicht](https://user-images.githubusercontent.com/17025347/46877603-8b4bd900-ce41-11e8-8413-17b95b797f22.png)

**Comment by ChristinaSi** [comment]
The top navigation bar is correctly implemented for the desktop version but not for the mobile version. Can we close this issue for now as we're currently not working on the mobile version @dboehmer ?

**Comment by dboehmer** [comment]
The pictures contain a lot more details, so I always hesitated to close this issue. If we agree that the main issue is solved, I’m glad to close it now.
