### ISSUE TITLE
Implement start page after login

### ISSUE THREAD

**Issue by ChristinaSi** [dboehmer/coocook#82]
Modify start page after login according to the picture in the appendix.

Important:

- A list of the public projects

- A list of the users private projects

- Project templates are provided

- Next steps are provided (as in the picture on the right)

![startseite](https://user-images.githubusercontent.com/17025347/46878115-b7b42500-ce42-11e8-9d1c-cebc3ddd440a.png)

**Comment by dboehmer** [comment]
Looks different than the projected picture above but all elements are there.
