### ISSUE TITLE
Choose free icon set

### ISSUE THREAD

**Issue by ChristinaSi** [dboehmer/coocook#89]
Choose an icon set that can be integrated in our software.
For example for the links to sign in and sign out.
Icons should be compatible to our license.

**Comment by CennoxX** [comment]
@dboehmer Can you assign this issue to me?

**Comment by dboehmer** [comment]
@CennoxX you need to accept the invitation for collaboration first, I think.

**Comment by dboehmer** [comment]
Just merged the `bootstrap` branch with the material design icons.
