### ISSUE TITLE
Replace locks in project overview

### ISSUE THREAD

**Issue by ChristinaSi** [dboehmer/coocook#91]
![coocook_schlosser](https://user-images.githubusercontent.com/17025347/48971303-f92a1980-f017-11e8-8344-a467e68f25c1.png)
In the project overview there are locks when creating or showing private projects. Remove them and replace them with some alternativ mark that this project is private.

**Comment by dboehmer** [comment]
needs alternative icon, probably from #89

**Comment by dboehmer** [comment]
![image](https://user-images.githubusercontent.com/116007/103564355-a55cb080-4ebe-11eb-8f96-32188e572a90.png)

Solved, I think.
