### ISSUE TITLE
Internal server error when deleting project

### ISSUE THREAD

**Issue by ChristinaSi** [dboehmer/coocook#92]
When you try to delete a project and click the button delete an error message appears "Internal server error". 
![screenshot_server_error](https://user-images.githubusercontent.com/17025347/50373962-a6c42480-05e6-11e9-96a6-4c941f682832.png)

**Comment by dboehmer** [comment]
This was often triggered by a series of `DELETE FROM` SQL statements for deleting all the project data. Unfortunately the database layer didn't correctly just `JOIN` the related tables but retrieved all row IDs and then sent them back to delete them. It al blew up when the SQL statement became longer than allowed.

This should be solved with the major database fixups in the `fix-cascade-delete` branch that was merged in 76a9558b38fe7a84606f56e97ef737809f33b6aa.
